версия джавы и заодно UTF-8  в pom.xml
GitUser-J2817/AngryChess pull request #16
Opened 2018-01-17 17:15 UTC by Corpse456

2018-01-25 15:38 UTC, IlyaBeetle commented
Не я ревьювер =D

2018-01-29 15:26 UTC, amitrofanov82 requested changes
Давайте с пробелами\табами\отступами сделаем все красиво, и потом вмержим.

2018-01-29 15:26 UTC, amitrofanov82 commented on pom.xml
> +    	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
а чего отступы такие неровные?

2018-01-29 15:28 UTC, amitrofanov82 commented on pom.xml
> +    	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
и ещё один нюанс. Это не критично, но вообще старайтесь, чтобы каждый файл с кодом заканчивался пустой строкой. Видите там внизу гит тоже об этом просит. Если спросите на занятии почему, то там и расскажу.

2018-03-01 17:42 UTC, amitrofanov82 approved these changes

2018-03-01 17:43 UTC, merged